// Supabase Edge Function: accept-tenant-invite
//
// Public endpoint (no Authorization header — the tenant isn't logged in
// yet). A tenant who received an invite link (any channel: WhatsApp, SMS,
// email, in person) from their landlord lands on /join?token=... in the
// app and sets their own password here. This is the "self-registration"
// counterpart to create-tenant-login (where the OWNER sets the password
// instead) — both are valid ways to create a tenant's login.
//
// Mobile number is REQUIRED here (email is optional) — unlike the owner's
// own create-tenant-login flow, which allows either. A tenant setting up
// their own account should always end up reachable by phone (SMS/WhatsApp
// reminders, phone-based sign-in) even if they skip giving an email.
//
// Security: the only thing that authorizes this call is knowing a valid,
// unexpired invite_token — generated by the owner via fn_generate_tenant_invite
// (SECURITY DEFINER, checks tenants.owner_id = auth.uid() before minting
// one). This function uses the SERVICE ROLE key throughout (there is no
// caller session to scope an anon client to), so it must do its own
// narrow lookup (token + expiry + not already linked) before touching
// anything privileged.

// deno-lint-ignore-file no-explicit-any
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.112.3'
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}
function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function normalizePhone(identifier: string): string {
  const trimmed = identifier.trim()
  if (trimmed.startsWith('+')) return trimmed.replace(/[\s-]/g, '')
  const digits = trimmed.replace(/\D/g, '')
  if (digits.length === 10) return `+91${digits}`
  return `+${digits}`
}

interface Body {
  token: string
  phone: string
  email?: string
  password: string
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405)

  try {
    const body = (await req.json().catch(() => null)) as Body | null
    if (!body?.token || !body?.phone || !body?.password) {
      return jsonResponse({ error: 'token, phone and password are required' }, 400)
    }
    const phone = normalizePhone(body.phone)
    if (!/^\+[1-9]\d{6,14}$/.test(phone)) return jsonResponse({ error: 'Enter a valid mobile number.' }, 400)
    const email = body.email?.trim() ? body.email.trim().toLowerCase() : undefined
    if (email && !EMAIL_RE.test(email)) return jsonResponse({ error: 'Enter a valid email address.' }, 400)
    if (body.password.length < 8 || !/[a-zA-Z]/.test(body.password) || !/[0-9]/.test(body.password)) {
      return jsonResponse({ error: 'Password must be at least 8 characters, with a letter and a number.' }, 400)
    }

    const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

    const { data: tenant, error: tErr } = await admin
      .from('tenants')
      .select('id, owner_id, full_name, profile_id, invite_token_expires_at')
      .eq('invite_token', body.token)
      .maybeSingle()
    if (tErr) return jsonResponse({ error: tErr.message }, 500)
    if (!tenant) return jsonResponse({ error: 'This invite link is invalid.' }, 404)
    if ((tenant as any).profile_id) return jsonResponse({ error: 'This invite link has already been used.' }, 400)
    const expiresAt = (tenant as any).invite_token_expires_at
    if (!expiresAt || new Date(expiresAt).getTime() < Date.now()) {
      return jsonResponse({ error: 'This invite link has expired. Please ask your landlord to send a new one.' }, 400)
    }

    const { data: created, error: createErr } = await admin.auth.admin.createUser({
      phone,
      phone_confirm: true,
      ...(email ? { email, email_confirm: true } : {}),
      password: body.password,
      user_metadata: {
        full_name: (tenant as any).full_name,
        role: 'tenant',
        owner_id: (tenant as any).owner_id,
        phone,
      }
    })
    if (createErr || !created?.user) {
      return jsonResponse({ error: createErr?.message ?? 'Could not create the login.' }, 400)
    }

    const newUserId = created.user.id

    const { error: profileErr } = await admin.from('profiles').upsert({
      id: newUserId,
      role: 'tenant',
      full_name: (tenant as any).full_name,
      email: email ?? null,
      phone,
      owner_id: (tenant as any).owner_id,
    })
    if (profileErr) return jsonResponse({ error: `Login created but profile setup failed: ${profileErr.message}` }, 500)

    const { error: linkErr } = await admin
      .from('tenants')
      .update({
        profile_id: newUserId,
        invite_token: null,
        invite_token_expires_at: null,
        phone,
        ...(email ? { email } : {}),
      })
      .eq('id', (tenant as any).id)
    if (linkErr) return jsonResponse({ error: `Login created but tenant link failed: ${linkErr.message}` }, 500)

    return jsonResponse({ success: true, phone, email: email ?? null })
  } catch (err) {
    return jsonResponse({ error: (err as Error).message ?? 'Unexpected error' }, 500)
  }
})
